### Importing the file

In [2]:
import numpy as np

# Specify the path to your text file
file_path = r"C:\Users\omri.c\OneDrive - arberobotics\Desktop\Omri\University\מעבדה מערכות אוטונומיות\Files From The Lab\out.txt"

### Getting the position and angle of each iterate

In [3]:
# Read the text file
with open(file_path, 'r') as file:
    lines = file.readlines()

# Initialize empty lists to store the updated positions and angles
positions = []
angles = []

# Extract positions and angles from the lines
for line in lines:
    if 'Update pos_x and pos_y:' in line:
        # Extract the pos_x and pos_y values
        values = line.split(':')[1].strip().split('|')[0].strip()
        x, y = map(float, values[1:-1].split(','))
        positions.append([x, y])
        
        # Extract the angle value
        angle_value = line.split('-')[-1].strip()
        angles.append(float(angle_value))

# Convert the lists of positions and angles to NumPy arrays
positions_array = np.array(positions)
angles_array = np.array(angles)

# Print the resulting positions and angles arrays
print("Positions:")
print(positions_array)
print("Angles:")
print(angles_array)

Positions:
[[   0.      0.  ]
 [   0.      0.  ]
 [   0.      0.  ]
 ...
 [-135.76   55.43]
 [-136.68   54.93]
 [-137.43   54.53]]
Angles:
[  0.     0.     0.   ... 208.51 208.51 208.44]


In [9]:
import re

# Initialize empty lists to store the extracted values
point_numbers = []
remaining_dists = []
target_velocities_left = []
target_velocities_right = []
dist_to_next_point = []

# Extract values from the lines
for line in lines:
    if 'Reached point number' in line:
        point_number = int(line.split()[-1])
        point_numbers.append(point_number)
    
    if 'Remaining dist =' in line:
        remaining_dist = float(line.split()[-1])
        remaining_dists.append(remaining_dist)
    
    if 'target_velocity_left' in line:
        match = re.search(r'target_velocity_left\s*-\s*([\d.]+)', line)
        if match:
            target_velocity_left = float(match.group(1))
            target_velocities_left.append(target_velocity_left)

    if 'target_velocity_right' in line:
        match = re.search(r'target_velocity_right\s*-\s*([\d.]+)', line)
        if match:
            target_velocity_right = float(match.group(1))
            target_velocities_right.append(target_velocity_right)
    
    if 'dist -' in line:
        match = re.search(r"dist - ([\d.]+)", line)
        if match:
            dist = float(match.group(1))
            dist_to_next_point.append(dist)


# Convert the lists to NumPy arrays
point_numbers_array = np.array(point_numbers)
remaining_dists_array = np.array(remaining_dists)
target_velocities_left_array = np.array(target_velocities_left)
target_velocities_right_array = np.array(target_velocities_right)
dist_to_next_point_array = np.array(dist_to_next_point)

# Print the resulting arrays
print("Point Numbers:")
print(point_numbers_array)
print("Remaining Distances:")
print(remaining_dists_array)
print("Target Velocities (Left):")
print(target_velocities_left_array)
print("Target Velocities (Right):")
print(target_velocities_right_array)
print("dist to next point ")
print(dist_to_next_point_array)

Point Numbers:
[0 0 0 ... 4 4 4]
Remaining Distances:
[250.         250.         250.         ... 287.41078146 288.37336025
 289.15778288]
Target Velocities (Left):
[200. 200. 200. ... 200. 200. 200.]
Target Velocities (Right):
[200.         200.         200.         ... 166.00124022 164.09421418
 164.18850705]
dist to next point 
[ 50.          50.          50.         ... 287.41078146 288.37336025
 289.15778288]


### Showing the shape:

In [15]:
import plotly.graph_objects as go

# Create a scatter plot
fig = go.Figure(data=go.Scatter(x=positions_array[:, 0], y=positions_array[:, 1], mode='markers'))

# Set the axis labels
fig.update_layout(xaxis_title='X Position', yaxis_title='Y Position')

# Set the plot title
fig.update_layout(title='Robot Path')

# Show the plot
fig.show()


### Saveing the X and Y position to html file

In [16]:
import plotly.graph_objects as go

# Create a scatter plot
fig = go.Figure(data=go.Scatter(x=positions_array[:, 0], y=positions_array[:, 1], mode='markers'))

# Set the axis labels
fig.update_layout(xaxis_title='X Position', yaxis_title='Y Position')

# Set the plot title
fig.update_layout(title='Robot Path')

# Save the plot in offline mode
fig.write_html('robot_path.html')


### Showing desired angle and Velocity diff

In [60]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

velocity_diff = target_velocities_left_array - target_velocities_right_array

# Create a subplot grid with 2 rows and 1 column
fig = make_subplots(rows=2, cols=1)

# Add the angle trace to the first row
fig.add_trace(go.Scatter(y=angles_array[0:245], mode='lines', name='Angle'), row=1, col=1)

# Add the velocity difference trace to the second row
fig.add_trace(go.Scatter(y=velocity_diff[0:245], mode='lines', name='Velocity Diff'), row=2, col=1)

fig.add_trace(go.Scatter(x=positions_array[:245, 0], y=positions_array[:245, 1],name="X and Y position", mode='markers'))

# Set the axis labels for the first row
fig.update_xaxes(title_text='Iteration', row=1, col=1)
fig.update_yaxes(title_text='Angle', row=1, col=1)

# Set the axis labels for the second row
fig.update_xaxes(title_text='Iteration', row=2, col=1)
fig.update_yaxes(title_text='Velocity Diff', row=2, col=1)

# Set the plot title
fig.update_layout(title='Angle and Velocity Difference')

# Show the plot
fig.show()


# Save the plot in offline mode
fig.write_html('Angle and Velocity.html')


### Remaining distance

In [16]:
import plotly.graph_objects as go

# Create a figure
fig = go.Figure()

# Add the remaining distance trace
fig.add_trace(go.Scatter(y=remaining_dists_array[0:245], mode='lines', name='Total Remaining Distance In line'))
# fig.add_trace(go.Scatter(y=point_numbers_array[0:300], mode='lines', name='Point Number'))
fig.add_trace(go.Scatter(y=dist_to_next_point_array[0:245], mode='lines', name='Remaining Distance to next point'))
# Add the velocity difference trace to the second row

# Set the axis labels
fig.update_xaxes(title_text='Iteration')
fig.update_yaxes(title_text='Remaining Distance')

# Set the plot title
fig.update_layout(title='Remaining Distance - One line')

# Show the plot
fig.show()
